# Generated by Django 2.0.2 on 2018-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
